# Copyright (c) 2016 Dustin Doloff
# Licensed under Apache License v2.0

load("@rules_web//:web.bzl",
    "minify_js",
)

minify_js(
    name = "all_js",
    srcs = [ "all.js" ],
    visibility = [ "//visibility:public" ],
)
